export const DtArea = [
    { province: 'Sulawesi Selatan', city: 'Makassar', district: 'Makassar' },
    { province: 'Sulawesi Selatan', city: 'Makassar', district: 'Tamalanrea' },
    { province: 'Sulawesi Selatan', city: 'Makassar', district: 'Tamalate' },
    { province: 'Sulawesi Selatan', city: 'Makassar', district: 'Tallo' },
    { province: 'Sulawesi Selatan', city: 'Makassar', district: 'Manggala' },
    { province: 'Sulawesi Selatan', city: 'Makassar', district: 'Rappocini' },
    { province: 'Sulawesi Selatan', city: 'Makassar', district: 'Ujung Tanah' },
    { province: 'Sulawesi Selatan', city: 'Makassar', district: 'Mariso' },
    { province: 'Sulawesi Selatan', city: 'Makassar', district: 'Biringkanaya' },
    { province: 'Sulawesi Selatan', city: 'Makassar', district: 'Panakkukang' },
    { province: 'Sulawesi Selatan', city: 'Gowa', district: 'Sompa Opu' },
    { province: 'Sulawesi Selatan', city: 'Gowa', district: 'Bontonompo' },

    { province: 'Sulawesi Utara', city: 'Manado', district: 'Bunaken' },
    { province: 'Sulawesi Utara', city: 'Manado', district: 'Wenang' },
    { province: 'Sulawesi Utara', city: 'Manado', district: 'Malalayang' },
    { province: 'Sulawesi Utara', city: 'Manado', district: 'Mapanget' },
    { province: 'Sulawesi Utara', city: 'Manado', district: 'Paal Dua' },

    { province: 'Maluku', city: 'Ambon', district: 'Teluk Ambon' },
    { province: 'Maluku', city: 'Ambon', district: 'Baguala' },
    { province: 'Maluku', city: 'Ambon', district: 'Sirimau' },
    { province: 'Maluku', city: 'Ambon', district: 'Nusaniwe' },
    { province: 'Papua', city: 'Kota Jayapura', district: 'Jayapura Selatan' },
    { province: 'Papua', city: 'Kota Jayapura', district: 'Abepura' },
    { province: 'Papua', city: 'Kota Jayapura', district: 'Koya Barat' },
    { province: 'Papua', city: 'Jayapura', district: 'Sentani' },
    { province: 'Papua', city: 'Jayapura', district: 'Sentani Timur' },
    { province: 'Papua', city: 'Jayapura', district: 'Sentani Barat' },
    { province: 'Papua', city: 'Jayapura', district: 'Depapre' },
    { province: 'Papua', city: 'Kota Jayapura', district: 'Kota Jayapura' },
    { province: 'Papua Barat', city: 'Kota Sorong', district: 'Kota Sorong' },
    { province: 'Bali', city: 'Denpasar', district: 'Denpasar Timur' },
    { province: 'Bali', city: 'Denpasar', district: 'Denpasar Utara' },
    { province: 'Bali', city: 'Denpasar', district: 'Denpasar Selatan' },
    { province: 'Bali', city: 'Denpasar', district: 'Denpasar Barat' },
    { province: 'Bali', city: 'Badung', district: 'Kuta Selatan' },
    { province: 'Bali', city: 'Badung', district: 'Kuta Utara' },
    { province: 'Bali', city: 'Badung', district: 'Kuta' },
    { province: 'Bali', city: 'Tabanan', district: 'Tabanan' },
    { province: 'Bali', city: 'Tabanan', district: 'Kediri' },
    { province: 'DKI Jakarta', city: 'Jakarta Barat', district: 'Kebon Jeruk' },
    { province: 'DKI Jakarta', city: 'Jakarta Barat', district: 'Grogol Petamburan' },
    { province: 'DKI Jakarta', city: 'Jakarta Barat', district: 'Kembangan' },
    { province: 'DKI Jakarta', city: 'Jakarta Barat', district: 'Kalideres' },
    { province: 'DKI Jakarta', city: 'Jakarta Timur', district: 'Cakung' },
    { province: 'DKI Jakarta', city: 'Jakarta Timur', district: 'Jatinegara' },
    { province: 'DKI Jakarta', city: 'Jakarta Timur', district: 'Duren Sawit' },
    { province: 'DKI Jakarta', city: 'Jakarta Timur', district: 'Kramat Jati' },
    { province: 'DKI Jakarta', city: 'Jakarta Timur', district: 'Ciracas' },
    { province: 'DKI Jakarta', city: 'Jakarta Timur', district: 'Makasar' },
    { province: 'DKI Jakarta', city: 'Jakarta Timur', district: 'Matraman' },
    { province: 'DKI Jakarta', city: 'Jakarta Timur', district: 'Pulo Gadung' },
    { province: 'DKI Jakarta', city: 'Jakarta Selatan', district: 'Pancoran' },
    { province: 'DKI Jakarta', city: 'Jakarta Selatan', district: 'Kebayoran Baru' },
    { province: 'DKI Jakarta', city: 'Jakarta Selatan', district: 'Kebayoran Lama' },
    { province: 'DKI Jakarta', city: 'Jakarta Selatan', district: 'Tebet' },
    { province: 'DKI Jakarta', city: 'Jakarta Selatan', district: 'Pesanggrahan' },
    { province: 'DKI Jakarta', city: 'Jakarta Selatan', district: 'Cilandak' },
    { province: 'DKI Jakarta', city: 'Jakarta Selatan', district: 'Pasar Minggu' },
    { province: 'DKI Jakarta', city: 'Jakarta Selatan', district: 'Jagakarsa' },
    { province: 'DKI Jakarta', city: 'Jakarta Utara', district: 'Cilincing' },
    { province: 'DKI Jakarta', city: 'Jakarta Pusat', district: 'Tanah Abang' },
    { province: 'DKI Jakarta', city: 'Jakarta Pusat', district: 'Menteng' },
    { province: 'DKI Jakarta', city: 'Jakarta Pusat', district: 'Cempaka Putih' },
    { province: 'DKI Jakarta', city: 'Jakarta Pusat', district: 'Kemayoran' },
    { province: 'DKI Jakarta', city: 'Jakarta Pusat', district: 'Senen' },
    { province: 'DKI Jakarta', city: 'Jakarta Pusat', district: 'Johar Baru' },

    { province: 'Banten', city: 'Kota Tangerang', district: 'Cipondoh' },
    { province: 'Banten', city: 'Kota Tangerang', district: 'Ciledug' },
    { province: 'Banten', city: 'Kota Tangerang', district: 'Cibodas' },

    { province: 'Banten', city: 'Kota Tangerang Selatan', district: 'Ciputat' },
    { province: 'Banten', city: 'Kota Tangerang Selatan', district: 'Pamulang' },
    { province: 'Banten', city: 'Kota Tangerang Selatan', district: 'Pondok Aren' },
    { province: 'Banten', city: 'Kota Tangerang Selatan', district: 'Serpong' },
    { province: 'Banten', city: 'Kota Tangerang Selatan', district: 'Setu' },

    { province: 'Jawa Barat', city: 'Depok', district: 'Limo' },
    { province: 'Jawa Barat', city: 'Depok', district: 'Tapos' },
    { province: 'Jawa Barat', city: 'Depok', district: 'Pancoran Mas' },
    { province: 'Jawa Barat', city: 'Depok', district: 'Beji' },
    { province: 'Jawa Barat', city: 'Depok', district: 'Cilodong' },
    { province: 'Jawa Barat', city: 'Bogor', district: 'Bogor Barat' },
    { province: 'Jawa Barat', city: 'Bogor', district: 'Bogor Selatan' },
    { province: 'Jawa Barat', city: 'Bogor', district: 'Gunung Putri' },
    { province: 'Jawa Barat', city: 'Bekasi', district: 'Pondokgede' },
    { province: 'Jawa Barat', city: 'Bekasi', district: 'Jatiasih' },
    { province: 'Jawa Barat', city: 'Bekasi', district: 'Bantargebang' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Yogyakarta', district: 'Danurejan' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Yogyakarta', district: 'Gedongtengen' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Yogyakarta', district: 'Gondokusuman' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Yogyakarta', district: 'Gondomanan' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Yogyakarta', district: 'Jetis' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Yogyakarta', district: 'Kotagede' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Yogyakarta', district: 'Kraton' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Yogyakarta', district: 'Mantrijeron' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Yogyakarta', district: 'Mergangsan' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Yogyakarta', district: 'Ngampilan' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Yogyakarta', district: 'Pakualaman' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Yogyakarta', district: 'Tegalrejo' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Yogyakarta', district: 'Umbulharjo' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Yogyakarta', district: 'Wirobrajan' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Yogyakarta', district: 'Gedong Tengen' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Bantul', district: 'Banguntapan' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Bantul', district: 'Kasihan' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Bantul', district: 'Piyungan' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Bantul', district: 'Sewon' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Bantul', district: 'Sedayu' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Sleman', district: 'Depok' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Sleman', district: 'Mlati' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Sleman', district: 'Ngaglik' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Sleman', district: 'Sleman' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Sleman', district: 'Kalasan' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Sleman', district: 'Gamping' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Sleman', district: 'Godean' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Sleman', district: 'Sinduadi' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Sleman', district: 'Ngemplak' },
    { province: 'Daerah Istimewa Yogyakarta', city: 'Kulon Progo', district: 'Temon' },
];