export const DtArea = [
    //  { slug: 'benteng', title: 'Benteng'},
    //  { slug: 'wainitu', title: 'Wainitu'},
    { slug: 'kudamati', title: 'Kudamati', image: 'KynKT7D.webpm'},
    //  { slug: 'mangga-dua', title: 'Mangga Dua'},
    { slug: 'urimessing', title: 'Urimessing', image: 'x9oUf7x.webpm'},
    { slug: 'waihaong', title: 'Waihaong', image: 'dl3HaUX.webpm' },
    { slug: 'silale', title: 'Silale', image: 'pkt6aLg.webpm' },
    //  { slug: 'latuhalat', title: 'Latuhalat'},
    //  { slug: 'seilale', title: 'Seilale'},
    //  { slug: 'nusaniwe', title: 'Nusaniwe'},
    //  { slug: 'amahusu', title: 'Amahusu'},

    { slug: 'batu-merah', title: 'Batu Merah', image: 'Jdu3CNN.webpm' },
    { slug: 'hative-kecil', title: 'Hative Kecil', image: 'DiQuXts.webpm'},
    //  { slug: 'soya', title: 'Soya'},
    { slug: 'galala', title: 'Galala', image: 'MEL1RGi.webpm' },
    { slug: 'ahusen', title: 'Ahusen', image: 'LHGdpvG.webpm' },
    //  { slug: 'amantelu', title: 'Amantelu'},
    //  { slug: 'batu-gajah', title: 'Batu Gajah'},
    //  { slug: 'batu-meja', title: 'Batu Meja'},
    { slug: 'honipopu', title: 'Honipopu', image: 'SxJCFTL.webpm' },
    { slug: 'karang-panjang', title: 'Karpan', image: 'MJPv6M5.webpm' },
    { slug: 'pandan-kasturi', title: 'Pandan Kasturi', image: '4g4Lbyu.webpm' },
    //  { slug: 'rijali', title: 'Rijali'},
    //  { slug: 'uritetu', title: 'Uritetu'},
    //  { slug: 'waihoka', title: 'Waihoka'},

    { slug: 'halong', title: 'Halong', image: '0lu6aHK.webpm' },
    { slug: 'passo', title: 'Passo', image: 'rpIivfJ.webpm' },
    //  { slug: 'latta', title: 'Latta'},
    //  { slug: 'nania', title: 'Nania'},
    //  { slug: 'negeri-lama', title: 'Negeri Lama'},
    { slug: 'waiheru', title: 'Waiheru', image: 'ts7LHY7.webpm'},
    { slug: 'lateri', title: 'Lateri', image: 'VgDIeU0.webpm'},

    //  { slug: 'hative-besar', title: 'Hative Besar'},
    { slug: 'laha', title: 'Laha', image: 'qi2ktEL.webpm' },
    { slug: 'poka', title: 'Poka', image: '7v2aJ0z.webpm' },
    //  { slug: 'rumah-tiga', title: 'Rumah Tiga'},
    //  { slug: 'tawiri', title: 'Tawiri'},
     { slug: 'hunuth-durian-patah', title: 'Hunuth', image: 'PA1MJ74.webpm' },
    //  { slug: 'wayame', title: 'Wayame'},
    //  { slug: 'tihu', title: 'Tihu'},

    //  { slug: 'ema', title: 'Ema'},
    //  { slug: 'hatalai', title: 'Hatalai'},
    //  { slug: 'hutumury', title: 'Hutumury'},
    //  { slug: 'hukurila', title: 'Hukurila'},
    //  { slug: 'kilang', title: 'Kilang'},
    //  { slug: 'leahari', title: 'Leahari'},
    //  { slug: 'naku', title: 'Naku'},
    //  { slug: 'rutong', title: 'Rutong'},

    { slug: 'suli', title: 'Suli', image: '0utQPHq.webpm' },
    { slug: 'piru', title: 'Piru', image: 'jQtXqlw.webpm' },

    { slug: 'kota-sorong', title: 'Kota Sorong', image: 'DlD89ZQ.webpm' },
    { slug: 'jayapura-selatan', title: 'Jayapura Selatan', image: 'OIZx8du.webpm' },
    { slug: 'abepura', title: 'Abepura', image: 'L7JVrMH.webpm' }
];