export const Campus = [
    { id: 1, slug: 'universitas-sanata-dharma', name: 'Universitas Sanata Dharma', province: 'Daerah Istimewa Yogyakarta' },
    { id: 2, slug: 'universitas-gadjah-mada', name: 'Universitas Gadjah Mada', province: 'Daerah Istimewa Yogyakarta' },
    { id: 3, slug: 'universitas-negeri-yogyakarta', name: 'Universitas Negeri Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { id: 4, slug: 'universitas-mahasaraswati-denpasar', name: 'Universitas Mahasaraswati Denpasar', province: 'Bali' },
    { id: 5, slug: 'uin-sunan-kalijaga-yogyakarta', name: 'UIN Sunan Kalijaga Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { id: 6, slug: 'universitas-pgri-yogyakarta', name: 'Universitas PGRI Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { id: 7, slug: 'universitas-pattimura', name: 'Universitas Pattimura', province: 'Maluku' },
    { id: 8, slug: 'universitas-udayana', name: 'Universitas Udayana', province: 'Bali' },
    { id: 9, slug: 'universitas-warmadewa', name: 'Universitas Warmadewa', province: 'Bali' },
    { id: 10, slug: 'universitas-ahmad-dahlan', name: 'Universitas Ahmad Dahlan', province: 'Daerah Istimewa Yogyakarta' },
    { id: 11, slug: 'universitas-teknologi-yogyakarta', name: 'Universitas Teknologi Daerah Istimewa Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { id: 12, slug: 'universitas-islam-indonesia', name: 'Universitas Islam Indonesia', province: 'Daerah Istimewa Yogyakarta' },
    { id: 13, slug: 'asrd-msd-yogyakarta', name: 'ASRD MSD Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { id: 14, slug: 'sekolah-tinggi-seni-rupa-dan-desain-visi', name: 'Sekolah Tinggi Seni Rupa dan Desain Visi', province: 'Daerah Istimewa Yogyakarta' },
    { id: 15, slug: 'institut-transportasi-dan-logistik-trisakti', name: 'Institut Transportasi dan Logistik Trisakti', province: 'DKI Jakarta' },
    { id: 16, slug: 'universitas-kristen-indonesia', name: 'Universitas Kristen Indonesia', province: 'DKI Jakarta' },
    { id: 17, slug: 'universitas-muhammadiyah-yogyakarta', name: 'Universitas Muhammadiyah Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { id: 18, slug: 'universitas-pembangunan-nasional-veteran-yogyakarta', name: 'Universitas Pembangunan Nasional Veteran Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { id: 19, slug: 'institut-teknologi-yogyakarta', name: 'Institut Teknologi Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { id: 20, slug: 'sekolah-tinggi-pariwisata-ambarrukmo-yogyakarta', name: 'Sekolah Tinggi Pariwisata Ambarrukmo Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { id: 21, slug: 'politeknik-negeri-bali', name: 'Politeknik Negeri Bali', province: 'Bali' },
    { id: 22, slug: 'politeknik-atk-yogyakarta', name: 'Politeknik ATK Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { id: 23, slug: 'sekolah-tinggi-ilmu-kesehatan-akbidyo', name: 'Sekolah Tinggi Ilmu Kesehatan AKBIDYO', province: 'Daerah Istimewa Yogyakarta' },
    { id: 24, slug: 'institut-seni-indonesia-yogyakarta', name: 'Institut Seni Indonesia Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { id: 25, slug: 'stikes-wira-medika-bali', name: 'STIKes Wira Medika Bali', province: 'Bali' },
    { id: 26, slug: 'institut-pariwisata-dan-bisnis-internasional', name: 'Institut Pariwisata dan Bisnis Internasional', province: 'Bali' },
    { id: 27, slug: 'universitas-aisyiyah-yogyakarta', name: 'Universitas Aisyiyah Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { id: 28, slug: 'universitas-respati-yogyakarta', name: 'Universitas Respati Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { id: 29, slug: 'universitas-sarjanawiyata-tamansiswa', name: 'Universitas Sarjanawiyata Tamansiswa', province: 'Daerah Istimewa Yogyakarta' },
    { id: 30, slug: 'universitas-mercu-buana-meruya', name: 'Universitas Mercu Buana Meruya', province: 'DKI Jakarta' },
    { id: 31, slug: 'stie-ykpn-yogyakarta', name: 'STIE YKPN Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { id: 32, slug: 'universitas-kristen-immanuel', name: 'Universitas Kristen Immanuel', province: 'Daerah Istimewa Yogyakarta' },
    { id: 33, slug: 'itekes-bali', name: 'ITEKES Bali', province: 'Daerah Istimewa Yogyakarta' },
    { id: 34, slug: 'universitas-krisnadwipayana', name: 'Universitas Krisnadwipayana', province: 'Jawa Barat' },
    { id: 35, slug: 'instiper-yogyakarta', name: 'INSTIPER Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { id: 36, slug: 'universitas-tarumanagara', name: 'Universitas Tarumanagara', province: 'DKI Jakarta' },
    { id: 37, slug: 'universitas-kristen-krida-wacana', name: 'Universitas Kristen Krida Wacana', province: 'DKI Jakarta' },
    { id: 38, slug: 'universitas-trisakti', name: 'Universitas Trisakti', province: 'DKI Jakarta' },
    { id: 39, slug: 'universitas-amikom-yogyakarta', name: 'Universitas AMIKOM Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { id: 40, slug: 'universitas-mercu-buana-yogyakarta', name: 'Universitas Mercu Buana Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { id: 41, slug: 'universitas-mh.thamrin', name: 'Universitas MH.Thamrin', province: 'DKI Jakarta' },
    { id: 42, slug: 'universitas-indraprasta-pgri', name: 'Universitas Indraprasta PGRI', province: 'DKI Jakarta' },
    { id: 43, slug: 'universitas-alma-ata-yogyakarta', name: 'Universitas Alma Ata Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { id: 44, slug: 'universitas-negeri-jakarta', name: 'Universitas Negeri Jakarta', province: 'DKI Jakarta' },
    { id: 45, slug: 'universitas-hasanuddin', name: 'Universitas Hasanuddin', province: 'Sulawesi Selatan' },
    { id: 46, slug: 'universitas-negeri-makassar', name: 'Universitas Negeri Makassar', province: 'Sulawesi Selatan' },
    { id: 47, slug: 'politeknik-bosowa', name: 'Politeknik Bosowa', province: 'Sulawesi Selatan' },
    { id: 48, slug: 'universitas-atma-jaya-yogyakarta', name: 'Universitas Atma Jaya Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { id: 49, slug: 'universitas-sahid-jakarta', name: 'Universitas Sahid Jakarta', province: 'DKI Jakarta' },
    { id: 50, slug: 'sekolah-tinggi-ilmu-ekonomi-amkop-makassar', name: 'Sekolah Tinggi Ilmu Ekonomi Amkop Makassar', province: 'Sulawesi Selatan' },
    { id: 51, slug: 'stikes-mega-rezky', name: 'STIKES Mega Rezky', province: 'Sulawesi Selatan' },
    { id: 52, slug: 'akademi-kebidanan-minasa-upa', name: 'Akademi Kebidanan Minasa Upa', province: 'Sulawesi Selatan' },
]