export const Campus = [
    { slug: 'universitas-sanata-dharma', name: 'Universitas Sanata Dharma', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'universitas-gadjah-mada', name: 'Universitas Gadjah Mada', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'universitas-negeri-yogyakarta', name: 'Universitas Negeri Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'universitas-mahasaraswati-denpasar', name: 'Universitas Mahasaraswati Denpasar', province: 'Bali' },
    { slug: 'uin-sunan-kalijaga-yogyakarta', name: 'UIN Sunan Kalijaga Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'universitas-pgri-yogyakarta', name: 'Universitas PGRI Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'universitas-pattimura', name: 'Universitas Pattimura', province: 'Maluku' },
    { slug: 'universitas-udayana', name: 'Universitas Udayana', province: 'Bali' },
    { slug: 'universitas-warmadewa', name: 'Universitas Warmadewa', province: 'Bali' },
    { slug: 'universitas-ahmad-dahlan', name: 'Universitas Ahmad Dahlan', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'universitas-teknologi-yogyakarta', name: 'Universitas Teknologi Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'universitas-islam-indonesia', name: 'Universitas Islam Indonesia', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'asrd-msd-yogyakarta', name: 'ASRD MSD Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'sekolah-tinggi-seni-rupa-dan-desain-visi', name: 'Sekolah Tinggi Seni Rupa dan Desain Visi', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'institut-transportasi-dan-logistik-trisakti', name: 'Institut Transportasi dan Logistik Trisakti', province: 'DKI Jakarta' },
    { slug: 'universitas-kristen-indonesia', name: 'Universitas Kristen Indonesia', province: 'DKI Jakarta' },
    { slug: 'universitas-muhammadiyah-yogyakarta', name: 'Universitas Muhammadiyah Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'universitas-pembangunan-nasional-veteran-yogyakarta', name: 'Universitas Pembangunan Nasional Veteran Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'institut-teknologi-yogyakarta', name: 'Institut Teknologi Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'sekolah-tinggi-pariwisata-ambarrukmo-yogyakarta', name: 'Sekolah Tinggi Pariwisata Ambarrukmo Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'politeknik-negeri-bali', name: 'Politeknik Negeri Bali', province: 'Bali' },
    { slug: 'politeknik-atk-yogyakarta', name: 'Politeknik ATK Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'sekolah-tinggi-ilmu-kesehatan-akbidyo', name: 'Sekolah Tinggi Ilmu Kesehatan AKBIDYO', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'institut-seni-indonesia-yogyakarta', name: 'Institut Seni Indonesia Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'stikes-wira-medika-bali', name: 'STIKes Wira Medika Bali', province: 'Bali' },
    { slug: 'institut-pariwisata-dan-bisnis-internasional', name: 'Institut Pariwisata dan Bisnis Internasional', province: 'Bali' },
    { slug: 'universitas-aisyiyah-yogyakarta', name: 'Universitas Aisyiyah Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'universitas-respati-yogyakarta', name: 'Universitas Respati Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'universitas-sarjanawiyata-tamansiswa', name: 'Universitas Sarjanawiyata Tamansiswa', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'universitas-mercu-buana-meruya', name: 'Universitas Mercu Buana Meruya', province: 'DKI Jakarta' },
    { slug: 'stie-ykpn-yogyakarta', name: 'STIE YKPN Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'universitas-kristen-immanuel', name: 'Universitas Kristen Immanuel', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'itekes-bali', name: 'ITEKES Bali', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'universitas-krisnadwipayana', name: 'Universitas Krisnadwipayana', province: 'Jawa Barat' },
    { slug: 'institut-pertanian-stiper-yogyakarta', name: 'Institut Pertanian Stiper Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'universitas-tarumanagara', name: 'Universitas Tarumanagara', province: 'DKI Jakarta' },
    { slug: 'universitas-kristen-krida-wacana', name: 'Universitas Kristen Krida Wacana', province: 'DKI Jakarta' },
    { slug: 'universitas-trisakti', name: 'Universitas Trisakti', province: 'DKI Jakarta' },
    { slug: 'universitas-amikom-yogyakarta', name: 'Universitas AMIKOM Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'universitas-mercu-buana-yogyakarta', name: 'Universitas Mercu Buana Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'universitas-mh.thamrin', name: 'Universitas MH.Thamrin', province: 'DKI Jakarta' },
    { slug: 'universitas-indraprasta-pgri', name: 'Universitas Indraprasta PGRI', province: 'DKI Jakarta' },
    { slug: 'universitas-alma-ata-yogyakarta', name: 'Universitas Alma Ata Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'universitas-negeri-jakarta', name: 'Universitas Negeri Jakarta', province: 'DKI Jakarta' },
    { slug: 'universitas-hasanuddin', name: 'Universitas Hasanuddin', province: 'Sulawesi Selatan' },
    { slug: 'stikes-nani-hasanuddin', name: 'STIKES Nani Hasanuddin', province: 'Sulawesi Selatan' },
    { slug: 'universitas-kristen-indonesia-paulus', name: 'Universitas Kristen Indonesia Paulus', province: 'Sulawesi Selatan' },
    { slug: 'politeknik-kesehatan-makassar', name: 'Politeknik Kesehatan Makassar', province: 'Sulawesi Selatan' },
    { slug: 'politeknik-stia-lan-makassar', name: 'Politeknik STIA LAN Makassar', province: 'Sulawesi Selatan' },
    { slug: 'universitas-negeri-makassar', name: 'Universitas Negeri Makassar', province: 'Sulawesi Selatan' },
    { slug: 'politeknik-bosowa', name: 'Politeknik Bosowa', province: 'Sulawesi Selatan' },
    { slug: 'universitas-atma-jaya-yogyakarta', name: 'Universitas Atma Jaya Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'universitas-sahid-jakarta', name: 'Universitas Sahid Jakarta', province: 'DKI Jakarta' },
    { slug: 'sekolah-tinggi-ilmu-ekonomi-amkop-makassar', name: 'Sekolah Tinggi Ilmu Ekonomi Amkop Makassar', province: 'Sulawesi Selatan' },
    { slug: 'stikes-mega-rezky', name: 'STIKES Mega Rezky', province: 'Sulawesi Selatan' },
    { slug: 'akademi-kebidanan-minasa-upa', name: 'Akademi Kebidanan Minasa Upa', province: 'Sulawesi Selatan' },
    { slug: 'universitas-bosowa', name: 'Universitas Bosowa', province: 'Sulawesi Selatan' },
    { slug: 'universitas-muslim-indonesia', name: 'Universitas Muslim Indonesia', province: 'Sulawesi Selatan' },
    { slug: 'politeknik-ati-makassar', name: 'Politeknik ATI Makassar', province: 'Sulawesi Selatan' },
    { slug: 'stmik-akakom-yogyakarta', name: 'STMIK AKAKOM Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'pgsd-universitas-pattimura', name: 'PGSD Universitas Pattimura', province: 'Maluku' },
    { slug: 'universitas-undiknas', name: 'Universitas Undiknas', province: 'Bali' },
    { slug: 'poltekkes-kemenkes-makassar', name: 'Poltekkes Kemenkes Makassar', province: 'Sulawesi Selatan' },
    { slug: 'universitas-muhammadiyah-makassar', name: 'Universitas Muhammadiyah Makassar', province: 'Sulawesi Selatan' },
    { slug: 'stmik-handayani-makassar', name: 'STMIK Handayani Makassar', province: 'Sulawesi Selatan' },
    { slug: 'universitas-fajar', name: 'Universitas Fajar', province: 'Sulawesi Selatan' },
    { slug: 'stmik-professional-makassar', name: 'STMIK Professional Makassar', province: 'Sulawesi Selatan' },
    { slug: 'universitas-islam-negeri-alauddin-makassar', name: 'Universitas Islam Negeri Alauddin Makassar', province: 'Sulawesi Selatan' },
    { slug: 'universitas-indonesia', name: 'Universitas Indonesia', province: 'Jawa Barat' },
    { slug: 'sekolah-tinggi-teknologi-kedirgantaraan', name: 'Sekolah Tinggi Teknologi Kedirgantaraan', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'institut-teknologi-nasional-yogyakarta', name: 'Institut Teknologi Nasional Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'universitas-gunadarma', name: 'Universitas Gunadarma', province: 'DKI Jakarta' },
    { slug: 'stmik-umel-mandiri', name: 'STMIK Umel Mandiri', province: 'Papua' },
    { slug: 'universitas-cenderawasih', name: 'Universitas Cenderawasih', province: 'Papua' },
    { slug: 'universitas-ottow-geissler Papua', name: 'Universitas Ottow Geissler Papua', province: 'Papua' },
    { slug: 'stmik-primakara', name: 'STMIK Primakara', province: 'Bali' },
    { slug: 'universitas-pendidikan-ganesha', name: 'Universitas Pendidikan Ganesha', province: 'Bali' },
    { slug: 'institut-teknologi-dan-bisnis-stikom-ambon', name: 'Institut Teknologi dan Bisnis STIKOM Ambon', province: 'Maluku' },
    { slug: 'universitas-kristen-indonesia-maluku', name: 'Universitas Kristen Indonesia Maluku', province: 'Maluku' },
    { slug: 'sekolah-tinggi-ilmu-manajemen-yayasan-keluarga-pahlawan-negara', name: 'Sekolah Tinggi Ilmu Manajemen Yayasan Keluarga Pahlawan Negara', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'universitas-janabadra', name: 'Universitas Janabadra', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'universitas-nahdlatul-ulama-yogyakarta', name: 'Universitas Nahdlatul Ulama Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'universitas-jenderal-achmad-yani-yogyakarta', name: 'Universitas Jenderal Achmad Yani Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'sekolah-tinggi-pertanahan-nasional-yogyakarta', name: 'Sekolah Tinggi Pertanahan Nasional Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'poltekkes-kemenkes-yogyakarta', name: 'Poltekkes Kemenkes Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
    { slug: 'itb-stikom-bali', name: 'ITB STIKOM Bali', province: 'Bali' },
    { slug: 'politeknik-pariwisata-bali', name: 'Politeknik Pariwisata Bali', province: 'Bali' },
    { slug: 'institut-stiami-jakarta', name: 'Institut STIAMI Jakarta', province: 'DKI Jakarta' },
    { slug: 'universitas-bung-karno', name: 'Universitas Bung Karno', province: 'DKI Jakarta' },
]