export const Campus = [
    { id: 1, slug: 'universitas-sanata-dharma', name: 'Universitas Sanata Dharma', province: 'Yogyakarta' },
    { id: 2, slug: 'universitas-gadjah-mada', name: 'Universitas Gadjah Mada', province: 'Yogyakarta' },
    { id: 3, slug: 'universitas-negeri-yogyakarta', name: 'Universitas Negeri Yogyakarta', province: 'Yogyakarta' },
    { id: 4, slug: 'universitas-mahasaraswati-denpasar', name: 'Universitas Mahasaraswati Denpasar', province: 'Bali' },
    { id: 5, slug: 'uin-sunan-kalijaga-yogyakarta', name: 'UIN Sunan Kalijaga Yogyakarta', province: 'Yogyakarta' },
    { id: 6, slug: 'universitas-pgri-yogyakarta', name: 'Universitas PGRI Yogyakarta', province: 'Yogyakarta' },
    { id: 7, slug: 'universitas-pattimura', name: 'Universitas Pattimura', province: 'Maluku' },
    { id: 8, slug: 'universitas-udayana', name: 'Universitas Udayana', province: 'Bali' },
    { id: 9, slug: 'universitas-warmadewa', name: 'Universitas Warmadewa', province: 'Bali' },
    { id: 10, slug: 'universitas-ahmad-dahlan', name: 'Universitas Ahmad Dahlan', province: 'Yogyakarta' },
    { id: 11, slug: 'universitas-teknologi-yogyakarta', name: 'Universitas Teknologi Yogyakarta', province: 'Yogyakarta' },
    { id: 12, slug: 'universitas-islam-indonesia', name: 'Universitas Islam Indonesia', province: 'Yogyakarta' },
    { id: 13, slug: 'asrd-msd-yogyakarta', name: 'ASRD MSD Yogyakarta', province: 'Yogyakarta' },
    { id: 14, slug: 'sekolah-tinggi-seni-rupa-dan-desain-visi', name: 'Sekolah Tinggi Seni Rupa dan Desain Visi', province: 'Yogyakarta' },
    { id: 15, slug: 'institut-transportasi-dan-logistik-trisakti', name: 'Institut Transportasi dan Logistik Trisakti', province: 'Jakarta Timur' },
    { id: 16, slug: 'universitas-kristen-indonesia', name: 'Universitas Kristen Indonesia', province: 'Jakarta Timur' },
    { id: 17, slug: 'universitas-muhammadiyah-yogyakarta', name: 'Universitas Muhammadiyah Yogyakarta', province: 'Yogyakarta' },
    { id: 18, slug: 'universitas-pembangunan-nasional-veteran-yogyakarta', name: 'Universitas Pembangunan Nasional Veteran Yogyakarta', province: 'Yogyakarta' },
    { id: 19, slug: 'institut-teknologi-yogyakarta', name: 'Institut Teknologi Yogyakarta', province: 'Yogyakarta' },
    { id: 20, slug: 'sekolah-tinggi-pariwisata-ambarrukmo-yogyakarta', name: 'Sekolah Tinggi Pariwisata Ambarrukmo Yogyakarta', province: 'Yogyakarta' },
    { id: 21, slug: 'politeknik-negeri-bali', name: 'Politeknik Negeri Bali', province: 'Bali' },
    { id: 22, slug: 'politeknik-atk-yogyakarta', name: 'Politeknik ATK Yogyakarta', province: 'Yogyakarta' },
    { id: 23, slug: 'sekolah-tinggi-ilmu-kesehatan-akbidyo', name: 'Sekolah Tinggi Ilmu Kesehatan AKBIDYO', province: 'Yogyakarta' },
    { id: 24, slug: 'institut-seni-indonesia-yogyakarta', name: 'Institut Seni Indonesia Yogyakarta', province: 'Yogyakarta' },
    { id: 25, slug: 'stikes-wira-medika-bali', name: 'STIKes Wira Medika Bali', province: 'Bali' },
    { id: 26, slug: 'institut-pariwisata-dan-bisnis-internasional', name: 'Institut Pariwisata dan Bisnis Internasional', province: 'Bali' },
    { id: 27, slug: 'universitas-aisyiyah-yogyakarta', name: 'Universitas Aisyiyah Yogyakarta', province: 'Yogyakarta' },
    { id: 28, slug: 'universitas-respati-yogyakarta', name: 'Universitas Respati Yogyakarta', province: 'Yogyakarta' },
    { id: 29, slug: 'universitas-sarjanawiyata-tamansiswa', name: 'Universitas Sarjanawiyata Tamansiswa', province: 'Yogyakarta' },
    { id: 30, slug: 'universitas-mercu-buana-meruya', name: 'Universitas Mercu Buana Meruya', province: 'Jakarta Barat' },
    { id: 31, slug: 'stie-ykpn-yogyakarta', name: 'STIE YKPN Yogyakarta', province: 'Yogyakarta' },
    { id: 32, slug: 'universitas-kristen-immanuel', name: 'Universitas Kristen Immanuel', province: 'Yogyakarta' },
    { id: 33, slug: 'itekes-bali', name: 'ITEKES Bali', province: 'Yogyakarta' },
    { id: 34, slug: 'universitas-krisnadwipayana', name: 'Universitas Krisnadwipayana', province: 'Jawa Barat' },
    { id: 35, slug: 'instiper-yogyakarta', name: 'INSTIPER Yogyakarta', province: 'Yogyakarta' },
    { id: 36, slug: 'universitas-aisyiyah-yogyakarta', name: 'Universitas Aisyiyah Yogyakarta', province: 'Yogyakarta' }
]