export const DtProvinsi = [
    { title: 'DKI Jakarta', slug: 'dki-jakarta' },
    { title: 'Banten', slug: 'banten' },
    { title: 'Bali', slug: 'bali' },
    { title: 'Maluku', slug: 'maluku' },
    { title: 'Papua', slug: 'papua' },
    { title: 'Papua Barat', slug: 'papua-barat' },
    { title: 'Jawa Barat', slug: 'jawa-barat' },
    { title: 'Jawa Timur', slug: 'jawa-timur' },
    { title: 'Jawa Tengah', slug: 'jawa-tengah' },
    { title: 'Daerah Istimewa Yogyakarta', slug: 'daerah-istimewa-yogyakarta' },
    { title: 'Sulawesi Selatan', slug: 'sulawesi-selatan' },
    { title: 'Sulawesi Utara', slug: 'sulawesi-utara' },
    { title: 'Sumatera Utara', slug: 'sumatera-utara' },
]